# Generated by Django 5.0.6 on 2024-07-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_product_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='farmer',
        ),
    ]
