# Generated by Django 5.0.6 on 2024-07-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_product_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='farmer',
        ),
        migrations.AddField(
            model_name='product',
            name='farmer_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
