# Generated by Django 5.0.6 on 2024-07-30 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_product_farmer_product_farmer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='farmer_id',
        ),
        migrations.AddField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp.farmer'),
            preserve_default=False,
        ),
    ]
