# Generated by Django 5.0.6 on 2024-08-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_product_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
    ]
