# Generated by Django 5.0.6 on 2024-08-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_price_chart_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_chart',
            name='category',
        ),
    ]
