# Generated by Django 5.0.6 on 2024-08-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_price_chart_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_chart',
            name='quantity',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
