# Generated by Django 5.0.6 on 2024-08-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_price_chart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_chart',
            name='product',
        ),
        migrations.AddField(
            model_name='price_chart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='price_chart_images/'),
        ),
        migrations.AddField(
            model_name='price_chart',
            name='product_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
