# Generated by Django 5.0.6 on 2024-08-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_remove_price_chart_product_price_chart_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
