# Generated by Django 5.0.6 on 2024-08-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_rename_price_cart_total_price_remove_cart_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
