# Generated by Django 5.0.6 on 2024-08-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_category_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_name',
        ),
    ]
