# Generated by Django 5.0.6 on 2024-08-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_alter_price_chart_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_chart',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
    ]
