# Generated by Django 5.0.6 on 2024-08-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_alter_wishlist_unique_together_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
