# Generated by Django 5.0.6 on 2024-08-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_cartitem_delete_cartproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
