# Generated by Django 5.0.6 on 2024-08-20 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_product_common_name_product_form_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_chart',
            name='subcategory',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp.subcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price_chart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='price_charts/'),
        ),
        migrations.AlterField(
            model_name='price_chart',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
