# Generated by Django 5.0.6 on 2024-08-20 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_price_chart_subcategory_alter_price_chart_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_chart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='price_chart_images/'),
        ),
        migrations.AlterField(
            model_name='price_chart',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='price_chart',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subcategory'),
        ),
    ]
