# Generated by Django 5.0.6 on 2024-08-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_delete_orderdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
