# Generated by Django 5.0.6 on 2024-08-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_order_orderitem_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
