# Generated by Django 5.0.6 on 2024-08-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_payment_cart_delete_orderstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cart',
        ),
    ]
