# Generated by Django 5.0.6 on 2024-08-28 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_remove_payment_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.deliveryboy')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.payment')),
            ],
        ),
    ]
