# Generated by Django 5.0.6 on 2024-08-28 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0071_payment_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cart',
        ),
    ]
