# Generated by Django 5.0.6 on 2024-09-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0074_payment_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='quantity',
        ),
    ]
