# Generated by Django 5.0.6 on 2024-09-04 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0077_orderdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='quantity',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_details',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp.orderdetails'),
            preserve_default=False,
        ),
    ]
