# Generated by Django 5.0.6 on 2024-09-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0078_remove_payment_product_remove_payment_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryassignment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=100),
        ),
    ]
