# Generated by Django 5.0.6 on 2024-09-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0079_alter_deliveryassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryassignment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=100),
        ),
    ]
