# Generated by Django 5.0.6 on 2024-09-24 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0080_alter_deliveryassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.orderdetails'),
        ),
    ]
