# Generated by Django 5.0.6 on 2024-09-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0081_alter_payment_order_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quality_images/')),
                ('status', models.CharField(max_length=20)),
                ('reasons', models.TextField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
