# Generated by Django 5.0.6 on 2024-10-19 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0083_farmerpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.orderdetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='products',
            field=models.ManyToManyField(through='myapp.OrderProduct', to='myapp.product'),
        ),
    ]
